In [1]:
import matplotlib.pyplot as plt
import h5py
import os
import scipy.signal as signal
from scipy import sparse
from scipy.sparse.linalg import spsolve
import glob
import numpy as np
import shutil
from decimal import Decimal
from PIL import Image
import mne
import pandas as pd

In [2]:
df= pd.read_excel('IMPRINT.xlsx')
nihss= df
nihss= nihss.iloc[[1, 6, 8, 10, 13, 18], [9, 10, 11, 12, 13]]
nihss= np.array(nihss)
mrs= df

mrs= mrs.iloc[[1, 6, 8, 10, 13, 18], [14, 15, 16, 17, 18]]
mrs= np.array(mrs)
fma= df
fma= fma.iloc[[1, 6, 8, 10, 13, 18], [19, 20, 21, 22, 23]]
fma= np.array(fma)
chai= df
chai= chai.iloc[[1, 6, 8, 10, 13, 18], [24, 25, 26, 27, 28]]
chai= np.array(chai)
fma[3][4]= 57
fma[5][3]= 94
fma[5][4]= 100
print (fma)

[[120 120 124 126 126]
 [110 110 115 115 124]
 [108 108 111 119 120]
 [44 44 55 54 57]
 [76 96 122 123 123]
 [50 52 92 94 100]]
